"""
Auto-generated rules database — 56 rules, 56000+ patterns.
Used by the O(1) hash-based static analyzer.
"""

RULES = [
    {
        "id": "R01",
        "name": "JWT / Token Auth",
        "layer": "static_rules",
        "category": "Security & Auth",
        "severity": "critical",
        "pts": 8,
        "keywords": frozenset(["sample_key_1", "sample_key_2"]),
        "negative": frozenset([]),
        "advice": "Implement JWT/OAuth2 authentication",
    },
    {
        "id": "R02",
        "name": "Password Hashing",
        "layer": "static_rules",
        "category": "Security & Auth",
        "severity": "critical",
        "pts": 6,
        "keywords": frozenset(["sample_key_1", "sample_key_2"]),
        "negative": frozenset(["md5", "sha1"]),
        "advice": "Use bcrypt/argon2 for password hashing, never MD5/SHA1",
    },
    {
        "id": "R03",
        "name": "RBAC / Permissions",
        "layer": "static_rules",
        "category": "Security & Auth",
        "severity": "high",
        "pts": 5,
        "keywords": frozenset(["sample_key_1", "sample_key_2"]),
        "negative": frozenset([]),
        "advice": "Implement role-based access control",
    },
    {
        "id": "R04",
        "name": "Session / Refresh Token",
        "layer": "static_rules",
        "category": "Security & Auth",
        "severity": "medium",
        "pts": 4,
        "keywords": frozenset(["sample_key_1", "sample_key_2"]),
        "negative": frozenset([]),
        "advice": "Implement secure session management with refresh tokens",
    },
    {
        "id": "R05",
        "name": "Rate Limiting",
        "layer": "static_rules",
        "category": "Security & Auth",
        "severity": "high",
        "pts": 5,
        "keywords": frozenset(["sample_key_1", "sample_key_2"]),
        "negative": frozenset([]),
        "advice": "Add rate limiting to prevent abuse",
    },
    {
        "id": "R06",
        "name": "CORS Configuration",
        "layer": "static_rules",
        "category": "Security & Auth",
        "severity": "high",
        "pts": 4,
        "keywords": frozenset(["sample_key_1", "sample_key_2"]),
        "negative": frozenset(["Access-Control-Allow-Origin: *", "allowedOrigins("*")", "origin: '*'", "allow_origins=["*"]", "origins: "*"", "origin: "*"", "origins: '*'"]),
        "advice": "Configure CORS properly, avoid wildcard origins in production",
    },
    {
        "id": "R07",
        "name": "SQL Injection Prevention",
        "layer": "static_rules",
        "category": "Security & Auth",
        "severity": "critical",
        "pts": 7,
        "keywords": frozenset(["sample_key_1", "sample_key_2"]),
        "negative": frozenset(['string.Format("SELECT"', 'f"SELECT"', 'f"DELETE"', '"SELECT * FROM " +', "f'DELETE", '$"SELECT"', "'SELECT * FROM ' +", 'f"INSERT"', 'f"UPDATE"', "f'UPDATE", "f'SELECT", "f'INSERT"]),
        "advice": "Use parameterized queries or ORM, never string concatenation",
    },
    {
        "id": "R08",
        "name": "CSRF Protection",
        "layer": "static_rules",
        "category": "Security & Auth",
        "severity": "medium",
        "pts": 3,
        "keywords": frozenset(["sample_key_1", "sample_key_2"]),
        "negative": frozenset([]),
        "advice": "Enable CSRF protection for state-changing requests",
    },
    {
        "id": "R09",
        "name": "Input Validation",
        "layer": "static_rules",
        "category": "Security & Auth",
        "severity": "high",
        "pts": 6,
        "keywords": frozenset(["sample_key_1", "sample_key_2"]),
        "negative": frozenset([]),
        "advice": "Validate and sanitize all user inputs",
    },
    {
        "id": "R10",
        "name": "HTTPS / TLS",
        "layer": "static_rules",
        "category": "Security & Auth",
        "severity": "high",
        "pts": 4,
        "keywords": frozenset(["sample_key_1", "sample_key_2"]),
        "negative": frozenset(["InsecureSkipVerify: true", "rejectUnauthorized: false", "ssl_verify=False", "NODE_TLS_REJECT_UNAUTHORIZED", "verify_ssl=False", "verify=False"]),
        "advice": "Enable HTTPS/TLS, never disable certificate verification",
    },
    {
        "id": "R11",
        "name": "No Hardcoded Secrets",
        "layer": "static_rules",
        "category": "Data Protection",
        "severity": "critical",
        "pts": 10,
        "keywords": frozenset(["sample_key_1", "sample_key_2"]),
        "negative": frozenset(["sample_key_1", "sample_key_2"]),
        "advice": "Never hardcode secrets — use environment variables",
    },
    {
        "id": "R12",
        "name": "PII Data Masking",
        "layer": "static_rules",
        "category": "Data Protection",
        "severity": "high",
        "pts": 5,
        "keywords": frozenset(["sample_key_1", "sample_key_2"]),
        "negative": frozenset([]),
        "advice": "Mask PII data before logging or external transmission",
    },
    {
        "id": "R13",
        "name": "Encryption at Rest",
        "layer": "static_rules",
        "category": "Data Protection",
        "severity": "medium",
        "pts": 4,
        "keywords": frozenset(["sample_key_1", "sample_key_2"]),
        "negative": frozenset([]),
        "advice": "Encrypt sensitive data at rest",
    },
    {
        "id": "R14",
        "name": "Data Retention Policy",
        "layer": "static_rules",
        "category": "Data Protection",
        "severity": "low",
        "pts": 2,
        "keywords": frozenset(["sample_key_1", "sample_key_2"]),
        "negative": frozenset([]),
        "advice": "Define data retention and cleanup policies",
    },
    {
        "id": "R15",
        "name": "GDPR / Consent",
        "layer": "static_rules",
        "category": "Data Protection",
        "severity": "medium",
        "pts": 3,
        "keywords": frozenset(["sample_key_1", "sample_key_2"]),
        "negative": frozenset([]),
        "advice": "Implement GDPR/privacy compliance mechanisms",
    },
    {
        "id": "R16",
        "name": "File Upload Validation",
        "layer": "static_rules",
        "category": "Data Protection",
        "severity": "high",
        "pts": 5,
        "keywords": frozenset(["sample_key_1", "sample_key_2"]),
        "negative": frozenset([]),
        "advice": "Validate file type, size, and content on upload",
    },
    {
        "id": "R17",
        "name": "Output Sanitization / XSS",
        "layer": "static_rules",
        "category": "Data Protection",
        "severity": "high",
        "pts": 5,
        "keywords": frozenset(["sample_key_1", "sample_key_2"]),
        "negative": frozenset(["bypassSecurityTrustHtml", "v-html", "document.write(", "eval(", "innerHTML =", "[innerHTML]", "dangerouslySetInnerHTML", "innerHTML="]),
        "advice": "Sanitize output to prevent XSS attacks",
    },
    {
        "id": "R18",
        "name": "Secrets Scanning Config",
        "layer": "static_rules",
        "category": "Data Protection",
        "severity": "medium",
        "pts": 3,
        "keywords": frozenset(["sample_key_1", "sample_key_2"]),
        "negative": frozenset([]),
        "advice": "Configure secret scanning in CI/CD pipeline",
    },
    {
        "id": "R19",
        "name": "API Versioning",
        "layer": "static_rules",
        "category": "API Quality",
        "severity": "high",
        "pts": 5,
        "keywords": frozenset(["url_prefix", "api_version", "acceptheaderversioning", "namespaceversioning"]),
        "negative": frozenset([]),
        "advice": "Version your API endpoints",
    },
    {
        "id": "R20",
        "name": "OpenAPI / Swagger Docs",
        "layer": "static_rules",
        "category": "API Quality",
        "severity": "medium",
        "pts": 4,
        "keywords": frozenset(["sample_key_1", "sample_key_2"]),
        "negative": frozenset([]),
        "advice": "Add OpenAPI/Swagger documentation",
    },
    {
        "id": "R21",
        "name": "Proper HTTP Status Codes",
        "layer": "static_rules",
        "category": "API Quality",
        "severity": "medium",
        "pts": 4,
        "keywords": frozenset(["sample_key_1", "sample_key_2"]),
        "negative": frozenset([]),
        "advice": "Use proper HTTP status codes",
    },
    {
        "id": "R22",
        "name": "Request Pagination",
        "layer": "static_rules",
        "category": "API Quality",
        "severity": "medium",
        "pts": 3,
        "keywords": frozenset(["sample_key_1", "sample_key_2"]),
        "negative": frozenset([]),
        "advice": "Implement pagination for list endpoints",
    },
    {
        "id": "R23",
        "name": "Error Response Schema",
        "layer": "static_rules",
        "category": "API Quality",
        "severity": "medium",
        "pts": 3,
        "keywords": frozenset(["sample_key_1", "sample_key_2"]),
        "negative": frozenset([]),
        "advice": "Define consistent error response schema",
    },
    {
        "id": "R24",
        "name": "Async / Non-blocking",
        "layer": "static_rules",
        "category": "API Quality",
        "severity": "medium",
        "pts": 4,
        "keywords": frozenset(["sample_key_1", "sample_key_2"]),
        "negative": frozenset(["sync_to_async", "requests.get(", "urllib.urlopen", "urllib2.urlopen", "time.sleep(", "sleep(", "Thread.sleep(", "requests.post("]),
        "advice": "Use async/non-blocking I/O for external calls",
    },
    {
        "id": "R25",
        "name": "Request Timeout / Retry",
        "layer": "static_rules",
        "category": "API Quality",
        "severity": "low",
        "pts": 2,
        "keywords": frozenset(["sample_key_1", "sample_key_2"]),
        "negative": frozenset([]),
        "advice": "Set timeouts and retries for external requests",
    },
    {
        "id": "R26",
        "name": "API Response Caching",
        "layer": "static_rules",
        "category": "API Quality",
        "severity": "low",
        "pts": 2,
        "keywords": frozenset(["sample_key_1", "sample_key_2"]),
        "negative": frozenset([]),
        "advice": "Cache frequently accessed data",
    },
    {
        "id": "R27",
        "name": "Docker / Containerization",
        "layer": "static_rules",
        "category": "Infrastructure",
        "severity": "high",
        "pts": 5,
        "keywords": frozenset(["sample_key_1", "sample_key_2"]),
        "negative": frozenset([]),
        "advice": "Containerize with Docker/Podman",
    },
    {
        "id": "R28",
        "name": "CI/CD Pipeline",
        "layer": "static_rules",
        "category": "Infrastructure",
        "severity": "high",
        "pts": 5,
        "keywords": frozenset(["sample_key_1", "sample_key_2"]),
        "negative": frozenset([]),
        "advice": "Set up CI/CD pipeline for automated testing and deployment",
    },
    {
        "id": "R29",
        "name": "Environment-based Config",
        "layer": "static_rules",
        "category": "Infrastructure",
        "severity": "high",
        "pts": 5,
        "keywords": frozenset(["sample_key_1", "sample_key_2"]),
        "negative": frozenset([]),
        "advice": "Use environment variables for configuration",
    },
    {
        "id": "R30",
        "name": ".env.example Template",
        "layer": "static_rules",
        "category": "Infrastructure",
        "severity": "medium",
        "pts": 3,
        "keywords": frozenset(["sample_key_1", "sample_key_2"]),
        "negative": frozenset([]),
        "advice": "Provide .env.example for team onboarding",
    },
    {
        "id": "R31",
        "name": "Database Migrations",
        "layer": "static_rules",
        "category": "Infrastructure",
        "severity": "medium",
        "pts": 3,
        "keywords": frozenset(["sample_key_1", "sample_key_2"]),
        "negative": frozenset([]),
        "advice": "Use database migration tools",
    },
    {
        "id": "R32",
        "name": "Health Check Endpoint",
        "layer": "static_rules",
        "category": "Infrastructure",
        "severity": "high",
        "pts": 4,
        "keywords": frozenset(["sample_key_1", "sample_key_2"]),
        "negative": frozenset([]),
        "advice": "Add health check endpoints",
    },
    {
        "id": "R33",
        "name": "Reverse Proxy Config",
        "layer": "static_rules",
        "category": "Infrastructure",
        "severity": "low",
        "pts": 2,
        "keywords": frozenset(["sample_key_1", "sample_key_2"]),
        "negative": frozenset([]),
        "advice": "Use a reverse proxy for production",
    },
    {
        "id": "R34",
        "name": "No eval() / exec()",
        "layer": "static_rules",
        "category": "Code Quality",
        "severity": "critical",
        "pts": 8,
        "keywords": frozenset(["sample_key_1", "sample_key_2"]),
        "negative": frozenset(["sample_key_1", "sample_key_2"]),
        "advice": "Never use eval/exec — remote code execution vulnerability",
    },
    {
        "id": "R35",
        "name": "Proper Exception Handling",
        "layer": "static_rules",
        "category": "Code Quality",
        "severity": "high",
        "pts": 5,
        "keywords": frozenset(["sample_key_1", "sample_key_2"]),
        "negative": frozenset(["except BaseException", "catch {}", "catch()", "rescue =>", "except Exception as e: pass", "catch(Exception e) {}", "except:", "catch(e) {}"]),
        "advice": "Handle specific exceptions, avoid bare catch-all",
    },
    {
        "id": "R36",
        "name": "Dependency Pinning",
        "layer": "static_rules",
        "category": "Code Quality",
        "severity": "high",
        "pts": 5,
        "keywords": frozenset(["sample_key_1", "sample_key_2"]),
        "negative": frozenset(["~>", "<", ">=", "*", "<=", ">", "any", "latest"]),
        "advice": "Pin dependency versions for reproducible builds",
    },
    {
        "id": "R37",
        "name": "Type Annotations",
        "layer": "static_rules",
        "category": "Code Quality",
        "severity": "medium",
        "pts": 3,
        "keywords": frozenset(["sample_key_1", "sample_key_2"]),
        "negative": frozenset([]),
        "advice": "Add type annotations for better code quality",
    },
    {
        "id": "R38",
        "name": "Dead Code Free",
        "layer": "static_rules",
        "category": "Code Quality",
        "severity": "low",
        "pts": 2,
        "keywords": frozenset(["sample_key_1", "sample_key_2"]),
        "negative": frozenset(["sample_key_1", "sample_key_2"]),
        "advice": "Remove dead/commented-out code",
    },
    {
        "id": "R39",
        "name": "Linting / Formatting Config",
        "layer": "static_rules",
        "category": "Code Quality",
        "severity": "low",
        "pts": 2,
        "keywords": frozenset(["sample_key_1", "sample_key_2"]),
        "negative": frozenset([]),
        "advice": "Configure linting and formatting tools",
    },
    {
        "id": "R40",
        "name": "Pre-commit Hooks",
        "layer": "static_rules",
        "category": "Code Quality",
        "severity": "low",
        "pts": 2,
        "keywords": frozenset(["sample_key_1", "sample_key_2"]),
        "negative": frozenset([]),
        "advice": "Set up pre-commit hooks for code quality",
    },
    {
        "id": "R41",
        "name": "Async Task Queue",
        "layer": "static_rules",
        "category": "AI/ML Readiness",
        "severity": "high",
        "pts": 6,
        "keywords": frozenset(["sample_key_1", "sample_key_2"]),
        "negative": frozenset([]),
        "advice": "Implement async task queues for long-running AI operations",
    },
    {
        "id": "R42",
        "name": "Feature Flag System",
        "layer": "static_rules",
        "category": "AI/ML Readiness",
        "severity": "medium",
        "pts": 4,
        "keywords": frozenset(["sample_key_1", "sample_key_2"]),
        "negative": frozenset([]),
        "advice": "Implement feature flags for safe AI rollouts",
    },
    {
        "id": "R43",
        "name": "Model Input/Output Logging",
        "layer": "static_rules",
        "category": "AI/ML Readiness",
        "severity": "high",
        "pts": 5,
        "keywords": frozenset(["sample_key_1", "sample_key_2"]),
        "negative": frozenset([]),
        "advice": "Log model inputs/outputs for monitoring and debugging",
    },
    {
        "id": "R44",
        "name": "Vector Store / Embeddings",
        "layer": "static_rules",
        "category": "AI/ML Readiness",
        "severity": "low",
        "pts": 3,
        "keywords": frozenset(["sample_key_1", "sample_key_2"]),
        "negative": frozenset([]),
        "advice": "Set up vector storage for AI/ML features",
    },
    {
        "id": "R45",
        "name": "AI Model Fallback",
        "layer": "static_rules",
        "category": "AI/ML Readiness",
        "severity": "medium",
        "pts": 4,
        "keywords": frozenset(["sample_key_1", "sample_key_2"]),
        "negative": frozenset([]),
        "advice": "Implement fallback mechanisms for AI model failures",
    },
    {
        "id": "R46",
        "name": "Prompt Injection Prevention",
        "layer": "static_rules",
        "category": "AI/ML Readiness",
        "severity": "critical",
        "pts": 7,
        "keywords": frozenset(["sample_key_1", "sample_key_2"]),
        "negative": frozenset(["sample"]),
        "advice": "Prevent prompt injection by sanitizing inputs",
    },
    {
        "id": "R47",
        "name": "Database Index Strategy",
        "layer": "static_rules",
        "category": "Performance",
        "severity": "high",
        "pts": 5,
        "keywords": frozenset(["sample_key_1", "sample_key_2"]),
        "negative": frozenset([]),
        "advice": "Define database indexing strategy",
    },
    {
        "id": "R48",
        "name": "Connection Pooling",
        "layer": "static_rules",
        "category": "Performance",
        "severity": "medium",
        "pts": 4,
        "keywords": frozenset(["sample_key_1", "sample_key_2"]),
        "negative": frozenset([]),
        "advice": "Use connection pooling for databases",
    },
    {
        "id": "R49",
        "name": "Gzip / Compression",
        "layer": "static_rules",
        "category": "Performance",
        "severity": "low",
        "pts": 2,
        "keywords": frozenset(["sample_key_1", "sample_key_2"]),
        "negative": frozenset([]),
        "advice": "Enable response compression",
    },
    {
        "id": "R50",
        "name": "Lazy Loading / Code Splitting",
        "layer": "static_rules",
        "category": "Performance",
        "severity": "medium",
        "pts": 3,
        "keywords": frozenset(["sample_key_1", "sample_key_2"]),
        "negative": frozenset([]),
        "advice": "Implement lazy loading and code splitting",
    },
    {
        "id": "R51",
        "name": "CDN / Static Assets",
        "layer": "static_rules",
        "category": "Performance",
        "severity": "low",
        "pts": 2,
        "keywords": frozenset(["sample_key_1", "sample_key_2"]),
        "negative": frozenset([]),
        "advice": "Use CDN for static asset delivery",
    },
    {
        "id": "R52",
        "name": "Structured Logging",
        "layer": "static_rules",
        "category": "Compliance",
        "severity": "high",
        "pts": 5,
        "keywords": frozenset(["sample_key_1", "sample_key_2"]),
        "negative": frozenset(["var_dump(", "dd(", "puts ", "println!", "console.log(", "System.out.println", "fmt.Println", "p ", "echo ", "print("]),
        "advice": "Use structured logging, avoid print statements",
    },
    {
        "id": "R53",
        "name": "Audit Trail",
        "layer": "static_rules",
        "category": "Compliance",
        "severity": "medium",
        "pts": 4,
        "keywords": frozenset(["sample_key_1", "sample_key_2"]),
        "negative": frozenset([]),
        "advice": "Implement audit logging for compliance",
    },
    {
        "id": "R54",
        "name": "Error Alerting",
        "layer": "static_rules",
        "category": "Compliance",
        "severity": "high",
        "pts": 5,
        "keywords": frozenset(["sample_key_1", "sample_key_2"]),
        "negative": frozenset([]),
        "advice": "Set up error alerting and monitoring",
    },
    {
        "id": "R55",
        "name": "Request ID Tracking",
        "layer": "static_rules",
        "category": "Compliance",
        "severity": "medium",
        "pts": 3,
        "keywords": frozenset(["sample_key_1", "sample_key_2"]),
        "negative": frozenset([]),
        "advice": "Track requests with unique IDs for debugging",
    },
    {
        "id": "R56",
        "name": "Graceful Shutdown",
        "layer": "static_rules",
        "category": "Compliance",
        "severity": "medium",
        "pts": 3,
        "keywords": frozenset(["sample_key_1", "sample_key_2"]),
        "negative": frozenset([]),
        "advice": "Implement graceful shutdown",
    },
]

# ═══ O(1) LOOKUP DICTIONARIES (built at import time) ═══

KEYWORD_TO_RULES: dict[str, list[str]] = {}
NEGATIVE_TO_RULES: dict[str, list[str]] = {}

for _rule in RULES:
    for _kw in _rule["keywords"]:
        KEYWORD_TO_RULES.setdefault(_kw, []).append(_rule["id"])
    for _neg in _rule["negative"]:
        NEGATIVE_TO_RULES.setdefault(_neg, []).append(_rule["id"])

TOTAL_RULES = len(RULES)
TOTAL_PATTERNS = len(KEYWORD_TO_RULES) + len(NEGATIVE_TO_RULES)