"""
Auto-generated rules database — 56 rules, 2425+ patterns.
Used by the O(1) hash-based static analyzer.
"""

RULES = [
    {
        "id": "R01",
        "name": "JWT / Token Auth",
        "layer": "static_rules",
        "category": "Security & Auth",
        "severity": "critical",
        "pts": 8,
        "keywords": frozenset(["jwt", "jsonwebtoken", "PyJWT", "python-jose", "jose", "jws", "jwe", "jwk", "jwks", "access_token", "refresh_token", "id_token", "bearer", "Bearer", "auth_token", "api_token", "create_access_token", "create_token", "generate_token", "sign_token", "issue_token", "verify_token", "validate_token", "decode_token", "check_token", "parse_token", "token_required", "login_required", "auth_required", "authenticated", "is_authenticated", "JWTBearer", "HTTPBearer", "OAuth2PasswordBearer", "OAuth2PasswordRequestForm", "oauth2", "oauth", "openid", "oidc", "OpenIDConnect", "OIDC", "passport", "passport-jwt", "passport-local", "passport-oauth2", "express-jwt", "koa-jwt", "hapi-auth-jwt2", "fastify-jwt", "django-rest-framework-simplejwt", "djangorestframework-jwt", "django-oauth-toolkit", "flask-jwt-extended", "flask-login", "flask-security", "flask-httpauth", "fastapi-jwt-auth", "fastapi-users", "starlette-authentication", "spring-security", "spring-security-oauth2", "spring-boot-starter-security", "@nestjs/jwt", "@nestjs/passport", "@nestjs/auth", "next-auth", "NextAuth", "nuxt-auth", "@nuxtjs/auth", "auth0", "Auth0", "firebase-auth", "FirebaseAuth", "supabase.auth", "clerk", "Clerk", "okta", "Okta", "keycloak", "Keycloak", "cognito", "AmazonCognito", "aws-amplify", "Amplify.Auth", "IdentityServer", "Microsoft.AspNetCore.Authentication", "System.IdentityModel.Tokens.Jwt", "JwtSecurityToken", "JwtSecurityTokenHandler", "golang-jwt", "dgrijalva/jwt-go", "lestrrat-go/jwx", "ruby-jwt", "devise", "devise-jwt", "warden", "omniauth", "tymon/jwt-auth", "laravel-passport", "laravel-sanctum", "laravel-fortify", "nimbus-jose-jwt", "jjwt", "io.jsonwebtoken", "java-jwt", "auth0-java", "jsonwebtoken.sign", "jsonwebtoken.verify", "jsonwebtoken.decode", "jwt.encode", "jwt.decode", "jwt.sign", "jwt.verify", "JWTAuth", "JwtAuth", "TokenAuth", "BearerAuth", "ApiKeyAuth", "Authorization", "WWW-Authenticate", "X-Auth-Token", "X-Access-Token", "token_type", "expires_in", "grant_type", "client_credentials", "authorization_code", "implicit", "password_grant", "refresh_token_grant", "access_token_lifetime", "refresh_token_lifetime", "token_endpoint", "userinfo_endpoint", "authorization_endpoint", "jwks_uri", "RS256", "RS384", "RS512", "HS256", "HS384", "HS512", "ES256", "ES384", "ES512", "PS256", "claim", "claims", "iss", "sub", "aud", "exp", "nbf", "iat", "jti", "SecurityScheme", "ApiKey", "HttpBearerAuth", "SecurityRequirement", "Authenticated", "Authorize", "AllowAnonymous", "RequireAuthentication", "authenticate", "authentication", "authenticator", "AuthService", "AuthController", "login", "signin", "sign_in", "signIn", "logIn", "log_in", "logout", "signout", "sign_out", "signOut", "logOut", "log_out", "register", "signup", "sign_up", "signUp", "createAccount", "create_account", "session", "session_id", "sessionId", "session_token", "sessionToken", "cookie", "httponly", "HttpOnly", "secure_cookie", "SameSite", "csrf_token", "csrftoken", "anti_forgery", "antiforgery", "xsrf", "two_factor", "2fa", "mfa", "multi_factor", "totp", "hotp", "authenticator_app", "magic_link", "passwordless", "biometric", "webauthn", "fido2", "passkey", "sso", "single_sign_on", "SingleSignOn", "SAML", "saml2", "CAS", "ldap", "LDAP", "ActiveDirectory", "active_directory", "kerberos", "api_key", "apiKey", "ApiKey", "API_KEY", "x-api-key", "X-API-Key", "basic_auth", "BasicAuth", "HTTPBasic", "digest_auth", "DigestAuth", "token_blacklist", "token_whitelist", "revoke_token", "revoked_token", "rotate_token", "token_rotation", "sliding_session"]),
        "negative": frozenset([]),
        "advice": "Implement JWT/OAuth2 authentication",
    },
    {
        "id": "R02",
        "name": "Password Hashing",
        "layer": "static_rules",
        "category": "Security & Auth",
        "severity": "critical",
        "pts": 6,
        "keywords": frozenset(["bcrypt", "argon2", "pbkdf2", "scrypt", "hashpw", "gensalt", "checkpw", "password_hash", "hash_password", "verify_password", "check_password", "PasswordHasher", "make_password", "check_password_hash", "generate_password_hash", "werkzeug.security", "passlib", "CryptContext", "pbkdf2_sha256", "pbkdf2_sha512", "argon2id", "argon2i", "argon2d", "Argon2PasswordHasher", "BCryptPasswordEncoder", "PasswordEncoder", "DaoAuthenticationProvider", "bcryptjs", "bcrypt-nodejs", "bcrypt.hash", "bcrypt.compare", "crypto.scrypt", "crypto.pbkdf2", "crypto.createHash", "sodium.crypto_pwhash", "libsodium", "nacl", "password_digest", "has_secure_password", "authenticate", "Hash::make", "Hash::check", "Illuminate\\Hashing", "golang.org/x/crypto/bcrypt", "GenerateFromPassword", "CompareHashAndPassword", "password_verify", "password_hash_func", "crypt", "SecurePassword", "PasswordPolicy", "password_strength", "zxcvbn", "password_validator", "django.contrib.auth.hashers", "PBKDF2PasswordHasher", "BCryptSHA256PasswordHasher", "Rfc2898DeriveBytes", "HashAlgorithm", "SHA256CryptoServiceProvider", "MessageDigest", "SecretKeyFactory", "PBEKeySpec"]),
        "negative": frozenset(["md5(", "MD5(", "sha1(", "SHA1(", "sha1_hash", "md5_hash", "hashlib.md5", "hashlib.sha1", "MessageDigest.getInstance(\"MD5\")", "MessageDigest.getInstance(\"SHA-1\")", "crypto.createHash('md5')", "crypto.createHash('sha1')"]),
        "advice": "Use bcrypt/argon2 for password hashing, never MD5/SHA1",
    },
    {
        "id": "R03",
        "name": "RBAC / Permissions",
        "layer": "static_rules",
        "category": "Security & Auth",
        "severity": "high",
        "pts": 5,
        "keywords": frozenset(["role", "roles", "permission", "permissions", "is_admin", "is_superuser", "is_staff", "has_permission", "has_role", "check_permission", "require_role", "RoleChecker", "scope", "scopes", "authorize", "Authorize", "authorized", "forbidden", "AccessControl", "access_control", "acl", "ACL", "RBAC", "rbac", "ABAC", "abac", "policy", "policies", "PolicyDocument", "iam", "IAM", "can", "cannot", "ability", "Ability", "CanCan", "cancan", "Pundit", "pundit", "Gates", "Gate", "gate", "middleware_permission", "PermissionRequiredMixin", "LoginRequiredMixin", "UserPassesTestMixin", "IsAuthenticated", "IsAdminUser", "IsOwner", "AllowAny", "DjangoModelPermissions", "PermissionDenied", "UnauthorizedError", "ForbiddenError", "AccessDeniedError", "admin_required", "superuser_required", "staff_required", "manager_required", "role_required", "roles_required", "permission_required", "permissions_required", "@roles_accepted", "@roles_required", "@permission_required", "Roles", "RolesGuard", "RoleGuard", "PermissionsGuard", "AuthGuard", "UserRole", "AdminRole", "ModeratorRole", "EditorRole", "ViewerRole", "ROLE_ADMIN", "ROLE_USER", "ROLE_MODERATOR", "ROLE_EDITOR", "hasAuthority", "hasRole", "hasAnyRole", "PreAuthorize", "Secured", "@PreAuthorize", "@PostAuthorize", "@RolesAllowed", "@PermitAll", "@DenyAll", "claims_required", "groups_required", "tenant", "multi_tenant", "organization"]),
        "negative": frozenset([]),
        "advice": "Implement role-based access control",
    },
    {
        "id": "R04",
        "name": "Session / Refresh Token",
        "layer": "static_rules",
        "category": "Security & Auth",
        "severity": "medium",
        "pts": 4,
        "keywords": frozenset(["refresh_token", "refresh", "token_refresh", "rotate_refresh", "sliding_expiration", "session", "sessions", "session_id", "sessionId", "session_store", "session_middleware", "express-session", "cookie-session", "koa-session", "connect-session", "django.contrib.sessions", "SessionMiddleware", "SessionStore", "flask-session", "Flask-Session", "server_side_session", "redis-session", "connect-redis", "session-file-store", "httponly", "HttpOnly", "secure", "SameSite", "cookie_secure", "set_cookie", "setCookie", "delete_cookie", "clear_cookie", "revoke", "revoke_token", "blacklist", "token_blacklist", "blocklist", "invalidate", "invalidate_session", "destroy_session", "session_destroy", "remember_me", "rememberMe", "persistent_session", "keep_alive", "idle_timeout", "absolute_timeout", "session_timeout", "session_expiry"]),
        "negative": frozenset([]),
        "advice": "Implement secure session management with refresh tokens",
    },
    {
        "id": "R05",
        "name": "Rate Limiting",
        "layer": "static_rules",
        "category": "Security & Auth",
        "severity": "high",
        "pts": 5,
        "keywords": frozenset(["slowapi", "SlowAPI", "Limiter", "ratelimit", "rate_limit", "rate_limiting", "RateLimit", "throttle", "throttling", "Throttle", "ThrottleGuard", "UserRateThrottle", "@limiter", "@ratelimit", "@throttle", "@rate_limit", "express-rate-limit", "rateLimit", "express-slow-down", "express-brute", "rack-attack", "Rack::Attack", "rack-throttle", "django-ratelimit", "django-axes", "django-defender", "flask-limiter", "Flask-Limiter", "flask-talisman", "fastapi-limiter", "fastapi-throttle", "spring-boot-starter-cache", "@Cacheable", "bucket4j", "resilience4j.ratelimiter", "rate_limiter", "RateLimiter", "TokenBucket", "LeakyBucket", "SlidingWindow", "FixedWindow", "requests_per_minute", "requests_per_second", "rpm", "rps", "quota", "api_quota", "too_many_requests", "TooManyRequests", "429", "HTTP_429", "retry_after", "Retry-After", "X-RateLimit-Limit", "X-RateLimit-Remaining", "brute_force", "brute_force_protection", "login_attempts", "max_attempts", "lockout", "ip_whitelist", "ip_blacklist", "ip_ban", "ban_ip", "block_ip", "ddos", "DDoS", "anti_ddos", "waf", "WAF", "firewall", "CloudFlare", "cloudflare", "nginx_limit_req", "limit_req_zone", "limit_conn", "rate_limit_config"]),
        "negative": frozenset([]),
        "advice": "Add rate limiting to prevent abuse",
    },
    {
        "id": "R06",
        "name": "CORS Configuration",
        "layer": "static_rules",
        "category": "Security & Auth",
        "severity": "high",
        "pts": 4,
        "keywords": frozenset(["CORSMiddleware", "cors", "CORS", "@cross_origin", "cross_origin", "CrossOrigin", "allow_origins", "allowed_origins", "allowedOrigins", "origin_whitelist", "allow_methods", "allow_headers", "allow_credentials", "expose_headers", "Access-Control-Allow-Origin", "Access-Control-Allow-Methods", "Access-Control-Allow-Headers", "Access-Control-Allow-Credentials", "Access-Control-Max-Age", "Access-Control-Expose-Headers", "django-cors-headers", "corsheaders", "flask-cors", "Flask-CORS", "@EnableCors", "@CrossOrigin", "CorsRegistry", "CorsConfiguration", "Rack::Cors", "rack-cors", "cors-anywhere", "helmet", "Helmet", "@fastify/cors", "@koa/cors", "cors-middleware", "preflight", "OPTIONS", "preflightContinue", "preflightMaxAge"]),
        "negative": frozenset(["allow_origins=[\"*\"]", "allowedOrigins(\"*\")", "Access-Control-Allow-Origin: *", "origin: '*'", "origin: \"*\"", "origins: '*'", "origins: \"*\""]),
        "advice": "Configure CORS properly, avoid wildcard origins in production",
    },
    {
        "id": "R07",
        "name": "SQL Injection Prevention",
        "layer": "static_rules",
        "category": "Security & Auth",
        "severity": "critical",
        "pts": 7,
        "keywords": frozenset(["sqlalchemy", "SQLAlchemy", "motor", "pymongo", "MongoClient", "prisma", "Prisma", "ActiveRecord", "Sequel", "Ecto", "GORM", "gorm", "Hibernate", "JPA", "MyBatis", "TypeORM", "Sequelize", "Knex", "Bookshelf", "Objection", "Drizzle", "Kysely", "prepared_statement", "PreparedStatement", "parameterized", "parametrized", "bind_param", "bind_params", "bound_params", "named_params", "placeholders", "sanitize", "escape", "mysql_real_escape", "pg", "psycopg2", "asyncpg", "aiomysql", "aiosqlite", "databases", "Entity", "Repository", "QueryBuilder", "createQueryBuilder", "ORM", "orm", "object_relational", "ActiveModel", "DataMapper", "django.db.models", "Model.objects", "QuerySet", "F()", "Q()", "peewee", "tortoise", "Tortoise", "SQLModel", "sqlmodel", "Eloquent", "DB::table", "DB::select", "DB::raw", "Arel", "ActiveRecord::Base", "where", "find_by"]),
        "negative": frozenset(["f\"SELECT", "f\"INSERT", "f\"UPDATE", "f\"DELETE", "f'SELECT", "f'INSERT", "f'UPDATE", "f'DELETE", "\"SELECT * FROM \" +", "'SELECT * FROM ' +", "string.Format(\"SELECT", "$\"SELECT"]),
        "advice": "Use parameterized queries or ORM, never string concatenation",
    },
    {
        "id": "R08",
        "name": "CSRF Protection",
        "layer": "static_rules",
        "category": "Security & Auth",
        "severity": "medium",
        "pts": 3,
        "keywords": frozenset(["csrf", "csrftoken", "csrf_token", "csrfmiddleware", "CsrfViewMiddleware", "anti_forgery", "antiforgery", "AntiForgeryToken", "ValidateAntiForgeryToken", "samesite", "SameSite", "Strict", "Lax", "csrf_exempt", "csrf_protect", "X-CSRF-Token", "X-XSRF-Token", "XSRF", "xsrf", "_token", "_csrf", "csurf", "csrf-csrf", "tiny-csrf", "csrf-protection", "authenticity_token", "protect_from_forgery", "verify_authenticity_token", "csrf_field", "@csrf", "CsrfFilter", "CsrfTokenRepository"]),
        "negative": frozenset([]),
        "advice": "Enable CSRF protection for state-changing requests",
    },
    {
        "id": "R09",
        "name": "Input Validation",
        "layer": "static_rules",
        "category": "Security & Auth",
        "severity": "high",
        "pts": 6,
        "keywords": frozenset(["pydantic", "BaseModel", "Field(", "validator", "field_validator", "model_validator", "zod", "Zod", "z.string", "z.number", "z.object", "z.array", "z.enum", "joi", "Joi", "celebrate", "express-validator", "validationResult", "marshmallow", "Schema", "fields.String", "fields.Integer", "validate", "cerberus", "voluptuous", "jsonschema", "JSON_SCHEMA", "ajv", "Ajv", "class-validator", "class-transformer", "IsString", "IsEmail", "IsNotEmpty", "javax.validation", "@NotNull", "@NotBlank", "@Size", "@Valid", "@Pattern", "FluentValidation", "DataAnnotations", "Required", "StringLength", "Range", "ActiveModel::Validations", "validates", "validates_presence_of", "dry-validation", "dry-types", "reform", "sanitize", "sanitizer", "DOMPurify", "xss", "bleach", "clean", "strip_tags", "htmlspecialchars", "htmlentities", "escape_html", "input_filter", "InputFilter", "whitelist", "blacklist", "allowlist", "blocklist", "TypeGuard", "isinstance", "type_check", "runtime_checkable", "beartype", "io-ts", "superstruct", "yup", "valibot", "typebox", "arktype"]),
        "negative": frozenset([]),
        "advice": "Validate and sanitize all user inputs",
    },
    {
        "id": "R10",
        "name": "HTTPS / TLS",
        "layer": "static_rules",
        "category": "Security & Auth",
        "severity": "high",
        "pts": 4,
        "keywords": frozenset(["ssl_context", "ssl", "tls", "TLS", "SSL", "certfile", "keyfile", "ca_certs", "HTTPSRedirectMiddleware", "SECURE_SSL_REDIRECT", "force_ssl", "ssl_required", "https", "HTTPS", "http2", "HTTP2", "h2", "ALPN", "SNI", "certificate", "cert", "x509", "X509", "letsencrypt", "certbot", "acme", "ssl_verify", "verify_ssl", "CERT_REQUIRED", "PROTOCOL_TLS", "SecurityMiddleware", "HSTS", "Strict-Transport-Security", "max-age", "includeSubDomains", "preload", "upgrade-insecure-requests"]),
        "negative": frozenset(["verify=False", "verify_ssl=False", "ssl_verify=False", "NODE_TLS_REJECT_UNAUTHORIZED", "rejectUnauthorized: false", "InsecureSkipVerify: true"]),
        "advice": "Enable HTTPS/TLS, never disable certificate verification",
    },
    {
        "id": "R11",
        "name": "No Hardcoded Secrets",
        "layer": "static_rules",
        "category": "Data Protection",
        "severity": "critical",
        "pts": 10,
        "keywords": frozenset([]),
        "negative": frozenset(["SECRET_KEY = \"", "SECRET_KEY = '", "PASSWORD = \"", "PASSWORD = '", "password = \"", "password = '", "API_KEY = \"", "API_KEY = '", "api_key = \"", "api_key = '", "apiKey = \"", "apiKey = '", "sk" + "-", "pk_" + "live_", "pk_" + "test_", "sk_" + "live_", "sk_" + "test_", "rk_" + "live_", "rk_" + "test_", "AK" + "IA", "aws_access_key", "aws_secret_key", "AWS_SECRET", "AWS_ACCESS", "ghp" + "_", "gho" + "_", "ghu" + "_", "ghs" + "_", "ghr" + "_", "github" + "_pat_", "glpat" + "-", "glsa" + "-", "Bearer " + "eyJ", "token = \"eyJ", "token = 'eyJ", "mongodb+srv://", "mongodb://.*:.*@", "postgres://.*:.*@", "mysql://.*:.*@", "redis://.*:.*@", "amqp://.*:.*@", "PRIVATE_KEY", "private_key", "-----BEGIN RSA", "-----BEGIN EC", "-----BEGIN PRIVATE", "sendgrid_api_key", "SENDGRID_API_KEY", "SG" + ".", "mailgun_api_key", "twilio_auth_token", "TWILIO_AUTH", "AC" + "_", "stripe_secret", "STRIPE_SECRET", "SLACK_TOKEN", "xoxb" + "-", "xoxp" + "-", "xoxe" + "-", "xapp" + "-", "FIREBASE_", "firebase_config", "AIza" + "Sy", "OPENAI_API_KEY", "ANTHROPIC_API_KEY", "GROQ_API_KEY", "HF_TOKEN", "GOOGLE_API_KEY", "AZURE_KEY", "COHERE_API_KEY"]),
        "advice": "Never hardcode secrets — use environment variables",
    },
    {
        "id": "R12",
        "name": "PII Data Masking",
        "layer": "static_rules",
        "category": "Data Protection",
        "severity": "high",
        "pts": 5,
        "keywords": frozenset(["mask", "masked", "masking", "mask_email", "mask_phone", "mask_ssn", "mask_card", "redact", "redacted", "redacting", "redaction", "redact_pii", "redact_sensitive", "anonymize", "anonymized", "anonymization", "anonymise", "anonymised", "pseudonymize", "pseudonymized", "pseudonymization", "pseudonymise", "censor", "censored", "obfuscate", "obfuscated", "obfuscation", "pii", "PII", "personally_identifiable", "sensitive_data", "personal_data", "***", "****", "*****", "[REDACTED]", "[MASKED]", "[HIDDEN]", "data_classification", "data_sensitivity", "data_category", "encrypt_field", "EncryptedField", "encrypted_column", "FieldEncryption", "column_encryption", "always_encrypted", "TDE", "tokenize", "tokenization", "vault", "HashiCorp", "secrets_manager", "AWS_KMS", "Azure_Key_Vault", "GCP_KMS", "CloudHSM", "scrub", "sanitize_log", "filter_sensitive", "hide_sensitive"]),
        "negative": frozenset([]),
        "advice": "Mask PII data before logging or external transmission",
    },
    {
        "id": "R13",
        "name": "Encryption at Rest",
        "layer": "static_rules",
        "category": "Data Protection",
        "severity": "medium",
        "pts": 4,
        "keywords": frozenset(["cryptography", "fernet", "Fernet", "aes", "AES", "encrypt", "decrypt", "cipher", "Cipher", "CipherText", "plaintext", "ciphertext", "symmetric", "asymmetric", "RSA", "ECDSA", "Ed25519", "ChaCha20", "AES-256", "AES-128", "AES-GCM", "GCM", "CBC", "CTR", "ECB", "pycryptodome", "pycryptodomex", "nacl", "libsodium", "tweetnacl", "crypto.subtle", "SubtleCrypto", "Web_Crypto", "WebCrypto", "javax.crypto", "Cipher.getInstance", "SecretKeySpec", "System.Security.Cryptography", "Aes.Create", "RijndaelManaged", "OpenSSL", "openssl", "crypto", "node:crypto", "encryption_key", "master_key", "data_key", "key_derivation", "KDF", "envelope_encryption", "field_level_encryption", "client_side_encryption", "at_rest", "data_at_rest", "storage_encryption", "disk_encryption", "LUKS", "BitLocker", "FileVault", "dm-crypt"]),
        "negative": frozenset([]),
        "advice": "Encrypt sensitive data at rest",
    },
    {
        "id": "R14",
        "name": "Data Retention Policy",
        "layer": "static_rules",
        "category": "Data Protection",
        "severity": "low",
        "pts": 2,
        "keywords": frozenset(["delete_after", "ttl", "TTL", "expires_at", "expiry", "retention", "retention_policy", "purge", "cleanup", "clean_up", "prune", "archive", "archival", "data_lifecycle", "lifecycle_policy", "expiration", "expire", "auto_delete", "auto_purge", "scheduled_deletion", "soft_delete", "hard_delete", "tombstone", "deleted_at", "is_deleted", "mark_deleted", "right_to_deletion", "erasure", "data_destruction", "backup_retention", "log_retention", "audit_retention", "time_to_live", "maxAge", "max_age", "cache_ttl"]),
        "negative": frozenset([]),
        "advice": "Define data retention and cleanup policies",
    },
    {
        "id": "R15",
        "name": "GDPR / Consent",
        "layer": "static_rules",
        "category": "Data Protection",
        "severity": "medium",
        "pts": 3,
        "keywords": frozenset(["gdpr", "GDPR", "consent", "consent_given", "user_consent", "cookie_consent", "privacy_policy", "privacy", "terms_of_service", "data_processing", "right_to_erasure", "right_to_access", "right_to_rectification", "data_portability", "data_export", "export_data", "download_data", "subject_access_request", "SAR", "DSAR", "lawful_basis", "legitimate_interest", "explicit_consent", "opt_in", "opt_out", "data_controller", "data_processor", "Data_Protection_Officer", "DPO", "CCPA", "HIPAA", "PIPEDA", "LGPD", "POPIA", "PDPA", "APPI", "cookie_banner", "consent_manager", "OneTrust", "CookieBot", "cookieyes", "anonymize_user", "delete_user_data", "forget_me", "right_to_forget"]),
        "negative": frozenset([]),
        "advice": "Implement GDPR/privacy compliance mechanisms",
    },
    {
        "id": "R16",
        "name": "File Upload Validation",
        "layer": "static_rules",
        "category": "Data Protection",
        "severity": "high",
        "pts": 5,
        "keywords": frozenset(["content_type", "mimetype", "mime_type", "MIME", "file_type", "file_extension", "file_size", "max_size", "max_file_size", "MAX_UPLOAD", "upload_limit", "UploadFile", "FileField", "ImageField", "FileInput", "MultipartFile", "multipart", "multipart/form-data", "form-data", "enctype", "allowed_extensions", "ALLOWED_EXTENSIONS", "accept", "file_filter", "magic_bytes", "file_magic", "python-magic", "file-type", "mime-types", "antivirus", "virus_scan", "malware_scan", "ClamAV", "clamav", "upload_to", "storage_path", "secure_filename", "werkzeug.utils", "multer", "Multer", "busboy", "formidable", "express-fileupload", "CarrierWave", "ActiveStorage", "Paperclip", "Shrine", "FileInterceptor", "FilesInterceptor", "@UseInterceptors", "IFormFile", "ContentDisposition", "FileContentResult"]),
        "negative": frozenset([]),
        "advice": "Validate file type, size, and content on upload",
    },
    {
        "id": "R17",
        "name": "Output Sanitization / XSS",
        "layer": "static_rules",
        "category": "Data Protection",
        "severity": "high",
        "pts": 5,
        "keywords": frozenset(["bleach", "bleach.clean", "sanitize", "sanitizer", "sanitize_html", "DOMPurify", "dompurify", "createDOMPurify", "isomorphic-dompurify", "markupsafe", "Markup", "escape", "html.escape", "cgi.escape", "xss", "XSS", "cross_site_scripting", "xss_clean", "helmet", "Helmet", "csp", "Content-Security-Policy", "nonce", "strip_tags", "htmlspecialchars", "htmlentities", "encode_html", "SafeString", "mark_safe", "autoescape", "Jinja2", "autoescaping", "textContent", "createTextNode", "innerText", "React.createElement", "jsx", "tsx", "template_literal", "AntiXss", "HtmlSanitizer", "Ganss.Xss"]),
        "negative": frozenset(["dangerouslySetInnerHTML", "innerHTML =", "innerHTML=", "v-html", "bypassSecurityTrustHtml", "[innerHTML]", "document.write(", "eval("]),
        "advice": "Sanitize output to prevent XSS attacks",
    },
    {
        "id": "R18",
        "name": "Secrets Scanning Config",
        "layer": "static_rules",
        "category": "Data Protection",
        "severity": "medium",
        "pts": 3,
        "keywords": frozenset(["gitleaks", "git-secrets", "trufflehog", "detect-secrets", "talisman", ".gitleaks.toml", "gitleaks.toml", ".pre-commit-config", "pre-commit", "secret_scanner", "credential_scanner", "ggshield", "GitGuardian", "aws-vault", "sops", "mozilla-sops", "age-encryption", "1password-cli", "op", "bitwarden-cli", "bw", "doppler", "infisical", "dotenv-vault", "chamber", "hashicorp-vault", "vault", "Vault", "transit", ".gitignore", "secrets.yaml", "sealed_secret", "SealedSecret", "kubeseal", "external-secrets", "ExternalSecret"]),
        "negative": frozenset([]),
        "advice": "Configure secret scanning in CI/CD pipeline",
    },
    {
        "id": "R19",
        "name": "API Versioning",
        "layer": "static_rules",
        "category": "API Quality",
        "severity": "high",
        "pts": 5,
        "keywords": frozenset(["/v1/", "/v2/", "/v3/", "/v4/", "api-version", "APIVersion", "ApiVersion", "api_version", "version_prefix", "URL_PREFIX", "prefix=\"/api/v", "router_prefix", "versioning", "URLPathVersioning", "AcceptHeaderVersioning", "NamespaceVersioning", "HeaderVersioning", "QueryParameterVersioning", "MediaTypeVersioning", "VERSION_PARAM", "API_DEFAULT_VERSION", "DEFAULT_VERSION", "semver", "semantic_version"]),
        "negative": frozenset([]),
        "advice": "Version your API endpoints",
    },
    {
        "id": "R20",
        "name": "OpenAPI / Swagger Docs",
        "layer": "static_rules",
        "category": "API Quality",
        "severity": "medium",
        "pts": 4,
        "keywords": frozenset(["swagger", "Swagger", "openapi", "OpenAPI", "FastAPI(", "@ApiProperty", "@ApiOperation", "@ApiResponse", "@ApiTags", "@ApiBody", "@ApiParam", "@ApiQuery", "@ApiHeader", "redoc", "ReDoc", "swagger-ui", "SwaggerUI", "swagger-jsdoc", "swagger-autogen", "springdoc", "SpringDoc", "springfox", "Swashbuckle", "NSwag", "drf-spectacular", "drf-yasg", "flask-restx", "flask-apispec", "apispec", "openapi-generator", "openapi-typescript", "tsoa"]),
        "negative": frozenset([]),
        "advice": "Add OpenAPI/Swagger documentation",
    },
    {
        "id": "R21",
        "name": "Proper HTTP Status Codes",
        "layer": "static_rules",
        "category": "API Quality",
        "severity": "medium",
        "pts": 4,
        "keywords": frozenset(["status_code=400", "status_code=401", "status_code=403", "status_code=404", "status_code=409", "status_code=422", "status_code=429", "status_code=500", "status_code=201", "status_code=204", "HTTPException", "HttpException", "BadRequestException", "UnauthorizedException", "ForbiddenException", "NotFoundException", "ConflictException", "UnprocessableEntityException", "status.HTTP_", "HttpStatus", "StatusCodes", "HttpStatusCode", "StatusCode", "BadRequest", "Unauthorized", "Forbidden", "NotFound", "InternalServerError", "ServiceUnavailable", "Created", "NoContent", "Accepted"]),
        "negative": frozenset([]),
        "advice": "Use proper HTTP status codes",
    },
    {
        "id": "R22",
        "name": "Request Pagination",
        "layer": "static_rules",
        "category": "API Quality",
        "severity": "medium",
        "pts": 3,
        "keywords": frozenset(["limit", "offset", "skip", "page", "cursor", "per_page", "page_size", "pageSize", "page_number", "pageNumber", "paginate", "pagination", "Paginator", "PageNumberPagination", "LimitOffsetPagination", "CursorPagination", "has_next", "has_previous", "next_page", "prev_page", "total_pages", "total_count", "take", "first", "after", "before", "edges", "pageInfo", "relay", "infinite_scroll", "load_more"]),
        "negative": frozenset([]),
        "advice": "Implement pagination for list endpoints",
    },
    {
        "id": "R23",
        "name": "Error Response Schema",
        "layer": "static_rules",
        "category": "API Quality",
        "severity": "medium",
        "pts": 3,
        "keywords": frozenset(["error_code", "ErrorResponse", "APIError", "ApiError", "ApiException", "error_handler", "exception_handler", "@app.exception_handler", "@ExceptionHandler", "@ControllerAdvice", "GlobalExceptionHandler", "ErrorFilter", "AllExceptionsFilter", "problem_detail", "ProblemDetail", "RFC7807", "error_message", "error_detail", "error_type", "traceback_id", "request_id", "correlation_id"]),
        "negative": frozenset([]),
        "advice": "Define consistent error response schema",
    },
    {
        "id": "R24",
        "name": "Async / Non-blocking",
        "layer": "static_rules",
        "category": "API Quality",
        "severity": "medium",
        "pts": 4,
        "keywords": frozenset(["async def", "await", "asyncio", "aiohttp", "aiofiles", "httpx.AsyncClient", "AsyncClient", "async_generator", "async_iterator", "async with", "async for", "Promise", "async function", "async/await", "then(", "Promise.all", "Promise.allSettled", "Promise.race", "Observable", "RxJS", "rxjs", "reactor", "Flux", "Mono", "Coroutine", "goroutine", "go func", "channel", "chan", "tokio", "async-std", "futures", "CompletableFuture", "CompletionStage", "Deferred", "suspend", "withContext", "Dispatchers", "EventLoop", "event_loop", "uvloop", "trio", "anyio", "curio"]),
        "negative": frozenset(["time.sleep(", "Thread.sleep(", "sleep(", "requests.get(", "requests.post(", "urllib.urlopen", "urllib2.urlopen", "sync_to_async"]),
        "advice": "Use async/non-blocking I/O for external calls",
    },
    {
        "id": "R25",
        "name": "Request Timeout / Retry",
        "layer": "static_rules",
        "category": "API Quality",
        "severity": "low",
        "pts": 2,
        "keywords": frozenset(["timeout", "Timeout", "connect_timeout", "read_timeout", "request_timeout", "socket_timeout", "retry", "Retry", "retries", "max_retries", "retry_count", "backoff", "exponential_backoff", "tenacity", "urllib3.Retry", "HTTPAdapter", "retry_policy", "RetryPolicy", "Polly", "resilience4j", "circuit_breaker", "CircuitBreaker", "pybreaker", "aiobreaker"]),
        "negative": frozenset([]),
        "advice": "Set timeouts and retries for external requests",
    },
    {
        "id": "R26",
        "name": "API Response Caching",
        "layer": "static_rules",
        "category": "API Quality",
        "severity": "low",
        "pts": 2,
        "keywords": frozenset(["redis", "Redis", "memcached", "Memcached", "cache", "Cache", "@cache", "lru_cache", "functools.cache", "TTLCache", "cachetools", "@cached", "fastapi-cache", "flask-caching", "django.core.cache", "Rails.cache", "spring-cache", "@Cacheable", "@CacheEvict", "@CachePut", "ResponseCache", "OutputCache", "ETag", "If-None-Match", "Cache-Control", "max-age", "stale-while-revalidate", "CDN", "edge_cache", "CloudFront", "Varnish"]),
        "negative": frozenset([]),
        "advice": "Cache frequently accessed data",
    },
    {
        "id": "R27",
        "name": "Docker / Containerization",
        "layer": "static_rules",
        "category": "Infrastructure",
        "severity": "high",
        "pts": 5,
        "keywords": frozenset(["FROM", "EXPOSE", "WORKDIR", "COPY", "RUN", "CMD", "ENTRYPOINT", "Dockerfile", "docker-compose", "docker_compose", "container_name", "image:", "services:", "volumes:", "networks:", "ports:", "docker", "Docker", "podman", "Podman", "containerd", "buildah", "kaniko", "skopeo", "distroless", "multi-stage", "scratch", "alpine", "slim", "OCI", "container", "containerized", "containerize", "kubernetes", "k8s", "helm", "kustomize", "ArgoCD", "Flux"]),
        "negative": frozenset([]),
        "advice": "Containerize with Docker/Podman",
    },
    {
        "id": "R28",
        "name": "CI/CD Pipeline",
        "layer": "static_rules",
        "category": "Infrastructure",
        "severity": "high",
        "pts": 5,
        "keywords": frozenset([".github/workflows", "github-actions", "GitHub_Actions", "on: push", "on: pull_request", "jobs:", "steps:", "runs-on", "actions/checkout", "actions/setup-node", "actions/setup-python", ".gitlab-ci", "gitlab-ci.yml", "GitLab_CI", "pipeline:", "stages:", "Jenkinsfile", "Jenkins", "jenkins", "pipeline", "declarative_pipeline", "CircleCI", ".circleci", "circle.yml", "TravisCI", ".travis.yml", "azure-pipelines", "Azure_DevOps", "Bamboo", "TeamCity", "Buildkite", "Drone", "Concourse", "Tekton", "Harness", "Spinnaker", "CodePipeline", "CodeBuild", "CloudBuild"]),
        "negative": frozenset([]),
        "advice": "Set up CI/CD pipeline for automated testing and deployment",
    },
    {
        "id": "R29",
        "name": "Environment-based Config",
        "layer": "static_rules",
        "category": "Infrastructure",
        "severity": "high",
        "pts": 5,
        "keywords": frozenset(["os.environ", "os.getenv", "process.env", "dotenv", "python-dotenv", "load_dotenv", "dotenv_values", "BaseSettings", "pydantic-settings", "config", "Config", "ConfigParser", "configparser", "environment", "APP_ENV", "NODE_ENV", "RAILS_ENV", "FLASK_ENV", "DJANGO_SETTINGS_MODULE", "Spring.profiles", "application.yml", "application.properties", "appsettings.json", "IConfiguration", "ConfigurationBuilder", "viper", "Viper", "envconfig", "godotenv", "figaro", "chamber"]),
        "negative": frozenset([]),
        "advice": "Use environment variables for configuration",
    },
    {
        "id": "R30",
        "name": ".env.example Template",
        "layer": "static_rules",
        "category": "Infrastructure",
        "severity": "medium",
        "pts": 3,
        "keywords": frozenset([".env.example", ".env.sample", ".env.template", ".env.dist", ".env.development", ".env.production", ".env.test", ".env.local", "env_file", "envFile", "dotenv-flow", "direnv", ".envrc", "config.example", "settings.example"]),
        "negative": frozenset([]),
        "advice": "Provide .env.example for team onboarding",
    },
    {
        "id": "R31",
        "name": "Database Migrations",
        "layer": "static_rules",
        "category": "Infrastructure",
        "severity": "medium",
        "pts": 3,
        "keywords": frozenset(["alembic", "Alembic", "revision", "upgrade", "downgrade", "migration", "migrations", "migrate", "makemigrations", "db:migrate", "rails db:migrate", "flyway", "Flyway", "liquibase", "Liquibase", "knex.migrate", "sequelize-cli", "typeorm migration", "prisma migrate", "goose", "golang-migrate", "diesel migration", "FluentMigrator", "EF Migrations", "Add-Migration", "Update-Database", "Schema.create", "Schema.table", "CreateTable", "AlterTable", "AddColumn"]),
        "negative": frozenset([]),
        "advice": "Use database migration tools",
    },
    {
        "id": "R32",
        "name": "Health Check Endpoint",
        "layer": "static_rules",
        "category": "Infrastructure",
        "severity": "high",
        "pts": 4,
        "keywords": frozenset(["health", "healthz", "healthcheck", "health_check", "ping", "pong", "/status", "/ready", "readiness", "readinessProbe", "liveness", "livenessProbe", "startupProbe", "heartbeat", "alive", "up", "diagnostics", "monitoring", "uptime", "is_healthy"]),
        "negative": frozenset([]),
        "advice": "Add health check endpoints",
    },
    {
        "id": "R33",
        "name": "Reverse Proxy Config",
        "layer": "static_rules",
        "category": "Infrastructure",
        "severity": "low",
        "pts": 2,
        "keywords": frozenset(["nginx", "Nginx", "NGINX", "caddy", "Caddy", "traefik", "Traefik", "haproxy", "HAProxy", "envoy", "Envoy", "proxy_pass", "upstream", "load_balancer", "load_balance", "reverse_proxy", "ingress", "Ingress", "IngressController", "API_Gateway", "api_gateway", "Kong", "kong", "Tyk", "Ambassador"]),
        "negative": frozenset([]),
        "advice": "Use a reverse proxy for production",
    },
    {
        "id": "R34",
        "name": "No eval() / exec()",
        "layer": "static_rules",
        "category": "Code Quality",
        "severity": "critical",
        "pts": 8,
        "keywords": frozenset([]),
        "negative": frozenset(["eval(", "exec(", "execFile(", "new Function(", "compile(", "__import__(", "importlib.import_module", "setattr(", "getattr(", "globals()", "locals()", "subprocess.call(", "os.system(", "os.popen(", "child_process.exec", "child_process.spawn", "Runtime.getRuntime().exec", "Process.Start", "system(", "popen(", "shell_exec(", "passthru(", "proc_open("]),
        "advice": "Never use eval/exec — remote code execution vulnerability",
    },
    {
        "id": "R35",
        "name": "Proper Exception Handling",
        "layer": "static_rules",
        "category": "Code Quality",
        "severity": "high",
        "pts": 5,
        "keywords": frozenset(["except ValueError", "except TypeError", "except KeyError", "except AttributeError", "except IOError", "except FileNotFoundError", "except ConnectionError", "except TimeoutError", "except HTTPException", "catch(err", "catch(error", "catch (err", "catch (error", "catch(e)", "rescue =>", "rescue StandardError", "try-catch", "try-except", "try-finally", "error_handler", "exception_handler", "@app.exception_handler", "@ExceptionHandler", "@ControllerAdvice", "ErrorBoundary", "componentDidCatch"]),
        "negative": frozenset(["except:", "catch()", "catch {}", "catch(Exception e) {}", "rescue =>", "except Exception as e: pass", "catch(e) {}", "except BaseException"]),
        "advice": "Handle specific exceptions, avoid bare catch-all",
    },
    {
        "id": "R36",
        "name": "Dependency Pinning",
        "layer": "static_rules",
        "category": "Code Quality",
        "severity": "high",
        "pts": 5,
        "keywords": frozenset(["==", "===", "~=", "^", "lock", "Pipfile.lock", "poetry.lock", "package-lock.json", "yarn.lock", "pnpm-lock.yaml", "Gemfile.lock", "composer.lock", "Cargo.lock", "go.sum", "gradle.lockfile", "flake.lock", "bun.lockb", "pip freeze", "pip-compile", "pip-tools", "pipenv", "poetry", "pdm"]),
        "negative": frozenset([">=", "<=", ">", "<", "~>", "latest", "*", "any"]),
        "advice": "Pin dependency versions for reproducible builds",
    },
    {
        "id": "R37",
        "name": "Type Annotations",
        "layer": "static_rules",
        "category": "Code Quality",
        "severity": "medium",
        "pts": 3,
        "keywords": frozenset(["-> str", "-> int", "-> float", "-> bool", "-> list", "-> dict", "-> None", "-> Optional", "-> Union", "Optional[", "List[", "Dict[", "Set[", "Tuple[", "Sequence[", "Mapping[", "Callable[", "TypeVar", "Generic[", "Protocol", "runtime_checkable", "TypedDict", "NamedTuple", "dataclass", "@dataclass", "interface ", "Interface", "type ", "Type", "implements", "extends", "readonly", "Readonly", "Record", "Partial", "Required", "Pick", "Omit", "Exclude", "Extract", "NonNullable", "ReturnType", "Parameters", "InstanceType"]),
        "negative": frozenset([]),
        "advice": "Add type annotations for better code quality",
    },
    {
        "id": "R38",
        "name": "Dead Code Free",
        "layer": "static_rules",
        "category": "Code Quality",
        "severity": "low",
        "pts": 2,
        "keywords": frozenset([]),
        "negative": frozenset(["# def ", "# class ", "// function ", "// class ", "/* function", "/* class", "#def ", "#class ", "//function ", "//class ", "DEPRECATED", "deprecated", "@deprecated", "FIXME: remove", "TODO: remove", "TODO: delete", "FIXME: delete", "UNUSED", "unused", "DEAD_CODE", "dead_code"]),
        "advice": "Remove dead/commented-out code",
    },
    {
        "id": "R39",
        "name": "Linting / Formatting Config",
        "layer": "static_rules",
        "category": "Code Quality",
        "severity": "low",
        "pts": 2,
        "keywords": frozenset([".eslintrc", ".eslintrc.js", ".eslintrc.json", "eslint.config", "eslint", "ESLint", "pyproject.toml", ".prettierrc", "prettier", "Prettier", ".editorconfig", "black", "Black", "ruff", "Ruff", "isort", "autopep8", "yapf", "flake8", "pylint", "mypy", "pyright", "Pylance", "rubocop", "RuboCop", "standardrb", "gofmt", "goimports", "golangci-lint", "rustfmt", "clippy", "ktlint", "detekt", "checkstyle", "spotless", "scalafmt", "deno fmt", "biome", "Biome", "rome"]),
        "negative": frozenset([]),
        "advice": "Configure linting and formatting tools",
    },
    {
        "id": "R40",
        "name": "Pre-commit Hooks",
        "layer": "static_rules",
        "category": "Code Quality",
        "severity": "low",
        "pts": 2,
        "keywords": frozenset(["pre-commit", "pre_commit", ".pre-commit-config.yaml", "husky", "Husky", "lint-staged", "lefthook", "Lefthook", "overcommit", "git-hooks", "githooks", "commitlint", "commitizen", "conventional-commits", "semantic-release", "changesets", "standard-version"]),
        "negative": frozenset([]),
        "advice": "Set up pre-commit hooks for code quality",
    },
    {
        "id": "R41",
        "name": "Async Task Queue",
        "layer": "static_rules",
        "category": "AI/ML Readiness",
        "severity": "high",
        "pts": 6,
        "keywords": frozenset(["celery", "Celery", "arq", "dramatiq", "Dramatiq", "rq", "RQ", "huey", "BackgroundTasks", "background_task", "asyncio.create_task", "asyncio.gather", "asyncio.wait", "asyncio.ensure_future", "concurrent.futures", "ThreadPoolExecutor", "ProcessPoolExecutor", "task_queue", "job_queue", "message_queue", "worker", "Worker", "beat", "periodic_task", "crontab", "schedule", "APScheduler", "Scheduler", "BullMQ", "bull", "Queue", "agenda", "bee-queue", "kue", "sidekiq", "Sidekiq", "delayed_job", "ActiveJob", "Hangfire", "Quartz", "Spring_Batch"]),
        "negative": frozenset([]),
        "advice": "Implement async task queues for long-running AI operations",
    },
    {
        "id": "R42",
        "name": "Feature Flag System",
        "layer": "static_rules",
        "category": "AI/ML Readiness",
        "severity": "medium",
        "pts": 4,
        "keywords": frozenset(["feature_flag", "feature_flags", "FeatureFlag", "feature_toggle", "feature_switch", "ENABLE_AI", "ENABLE_ML", "AI_ENABLED", "ML_ENABLED", "launchdarkly", "LaunchDarkly", "flagsmith", "Flagsmith", "unleash", "Unleash", "split", "Split", "optimizely", "Optimizely", "configcat", "ConfigCat", "flipper", "Flipper", "rollout", "GrowthBook", "feature_management", "FeatureManagement", "is_feature_enabled", "is_enabled", "check_feature", "waffle", "django-waffle", "gargoyle", "Togglz"]),
        "negative": frozenset([]),
        "advice": "Implement feature flags for safe AI rollouts",
    },
    {
        "id": "R43",
        "name": "Model Input/Output Logging",
        "layer": "static_rules",
        "category": "AI/ML Readiness",
        "severity": "high",
        "pts": 5,
        "keywords": frozenset(["model_input", "model_output", "prediction_log", "inference_log", "prompt_log", "response_log", "langsmith", "LangSmith", "langfuse", "Langfuse", "mlflow", "MLflow", "wandb", "WandB", "Weights_and_Biases", "neptune", "Neptune", "comet", "Comet", "tensorboard", "TensorBoard", "experiment_tracking", "model_monitoring", "data_drift", "concept_drift", "model_performance", "A/B_test", "shadow_mode", "canary_deployment", "blue_green", "prometheus", "grafana", "opentelemetry", "tracing", "span", "trace"]),
        "negative": frozenset([]),
        "advice": "Log model inputs/outputs for monitoring and debugging",
    },
    {
        "id": "R44",
        "name": "Vector Store / Embeddings",
        "layer": "static_rules",
        "category": "AI/ML Readiness",
        "severity": "low",
        "pts": 3,
        "keywords": frozenset(["pinecone", "Pinecone", "weaviate", "Weaviate", "chroma", "ChromaDB", "qdrant", "Qdrant", "milvus", "Milvus", "pgvector", "pg_embedding", "faiss", "FAISS", "annoy", "Annoy", "hnswlib", "ScaNN", "lancedb", "LanceDB", "elasticsearch_knn", "opensearch_knn", "embedding", "embeddings", "Embeddings", "embed", "text-embedding", "sentence-transformers", "SentenceTransformer", "OpenAIEmbeddings", "CohereEmbeddings", "HuggingFaceEmbeddings", "vector_store", "VectorStore", "vector_db", "VectorDB", "similarity_search", "semantic_search", "nearest_neighbor", "knn", "cosine_similarity", "dot_product"]),
        "negative": frozenset([]),
        "advice": "Set up vector storage for AI/ML features",
    },
    {
        "id": "R45",
        "name": "AI Model Fallback",
        "layer": "static_rules",
        "category": "AI/ML Readiness",
        "severity": "medium",
        "pts": 4,
        "keywords": frozenset(["fallback", "Fallback", "fallback_model", "fallback_response", "default_response", "graceful_degradation", "retry_model", "model_fallback", "circuit_breaker", "CircuitBreaker", "bulkhead", "Bulkhead", "timeout_fallback", "error_fallback", "fail_safe", "failsafe", "fail_open", "fail_close", "dead_letter", "DLQ", "compensation", "saga", "saga_pattern", "rollback", "undo", "compensating_action", "alternative_model", "backup_model", "secondary_model", "primary_model"]),
        "negative": frozenset([]),
        "advice": "Implement fallback mechanisms for AI model failures",
    },
    {
        "id": "R46",
        "name": "Prompt Injection Prevention",
        "layer": "static_rules",
        "category": "AI/ML Readiness",
        "severity": "critical",
        "pts": 7,
        "keywords": frozenset(["sanitize_prompt", "clean_prompt", "validate_prompt", "prompt_template", "PromptTemplate", "ChatPromptTemplate", "SystemMessage", "HumanMessage", "AIMessage", "prompt_guard", "prompt_shield", "guardrails", "Guardrails", "NeMo_Guardrails", "rebuff", "Rebuff", "LLM_Guard", "llm_guard", "content_filter", "ContentFilter", "moderation", "Moderation", "content_moderation", "input_guard", "output_guard", "prompt_engineering", "system_prompt", "instruction_hierarchy", "delimiter", "boundary", "sandbox_prompt"]),
        "negative": frozenset(["user_input.*prompt", "f\".*{user", "f'.*{user", "prompt.*user_input", "prompt = user", "prompt = request", "prompt += user", "prompt += request", "format(user_input)", "format(request"]),
        "advice": "Prevent prompt injection by sanitizing inputs",
    },
    {
        "id": "R47",
        "name": "Database Index Strategy",
        "layer": "static_rules",
        "category": "Performance",
        "severity": "high",
        "pts": 5,
        "keywords": frozenset(["create_index", "createIndex", "ensureIndex", "Index(", "index=True", "db_index=True", "add_index", "IndexModel", "compound_index", "unique_index", "text_index", "sparse_index", "partial_index", "covering_index", "composite_index", "btree", "hash_index", "gin_index", "gist_index", "brin_index", "EXPLAIN", "explain", "query_plan", "slow_query", "query_optimization", "indexing_strategy"]),
        "negative": frozenset([]),
        "advice": "Define database indexing strategy",
    },
    {
        "id": "R48",
        "name": "Connection Pooling",
        "layer": "static_rules",
        "category": "Performance",
        "severity": "medium",
        "pts": 4,
        "keywords": frozenset(["pool", "Pool", "pool_size", "max_connections", "min_connections", "maxPoolSize", "minPoolSize", "connection_pool", "ConnectionPool", "pool_pre_ping", "pool_recycle", "pool_timeout", "create_pool", "create_engine", "engine", "Engine", "pgBouncer", "PgBouncer", "ProxySQL", "connection_limit", "max_overflow", "pool_class", "QueuePool", "NullPool", "StaticPool", "AsyncEngine", "create_async_engine"]),
        "negative": frozenset([]),
        "advice": "Use connection pooling for databases",
    },
    {
        "id": "R49",
        "name": "Gzip / Compression",
        "layer": "static_rules",
        "category": "Performance",
        "severity": "low",
        "pts": 2,
        "keywords": frozenset(["GZipMiddleware", "gzip", "Gzip", "brotli", "Brotli", "compression", "compress", "deflate", "zlib", "zstd", "lz4", "snappy", "Content-Encoding", "Accept-Encoding", "transfer-encoding", "shrink-ray", "express-compression", "rack-deflater"]),
        "negative": frozenset([]),
        "advice": "Enable response compression",
    },
    {
        "id": "R50",
        "name": "Lazy Loading / Code Splitting",
        "layer": "static_rules",
        "category": "Performance",
        "severity": "medium",
        "pts": 3,
        "keywords": frozenset(["React.lazy", "lazy(", "Suspense", "next/dynamic", "dynamic(", "import(", "loadable", "@loadable/component", "React.Suspense", "fallback", "code_splitting", "chunk", "splitChunks", "vendor_chunk", "route_based_splitting", "prefetch", "preload", "modulepreload", "webpackChunkName", "rollupOptions", "manualChunks", "tree_shaking", "treeShaking", "sideEffects", "purge", "dead_code_elimination"]),
        "negative": frozenset([]),
        "advice": "Implement lazy loading and code splitting",
    },
    {
        "id": "R51",
        "name": "CDN / Static Assets",
        "layer": "static_rules",
        "category": "Performance",
        "severity": "low",
        "pts": 2,
        "keywords": frozenset(["cdn", "CDN", "cloudfront", "CloudFront", "cloudflare", "Cloudflare", "akamai", "Akamai", "fastly", "Fastly", "staticfiles", "static_url", "STATIC_URL", "PUBLIC_URL", "ASSET_URL", "S3_BUCKET", "s3", "S3", "blob_storage", "cloud_storage", "GCS", "Azure_CDN", "KeyCDN", "BunnyCDN", "jsdelivr", "unpkg", "cdnjs", "assets_host", "asset_host", "media_url", "MEDIA_URL"]),
        "negative": frozenset([]),
        "advice": "Use CDN for static asset delivery",
    },
    {
        "id": "R52",
        "name": "Structured Logging",
        "layer": "static_rules",
        "category": "Compliance",
        "severity": "high",
        "pts": 5,
        "keywords": frozenset(["logging", "logger", "Logger", "getLogger", "logging.getLogger", "loguru", "structlog", "log4j", "Log4j", "log4net", "SLF4J", "Logback", "NLog", "Serilog", "winston", "pino", "bunyan", "morgan", "log.info", "log.error", "log.warn", "log.debug", "logger.info", "logger.error", "logger.warning", "logger.debug", "logging.info", "logging.error", "structured_logging", "json_logging", "log_format", "log_level", "LOG_LEVEL", "log_config", "ELK", "Elasticsearch", "Logstash", "Kibana", "Fluentd", "Fluent_Bit", "Datadog", "Splunk", "Papertrail", "Loggly", "CloudWatch_Logs", "GCP_Logging"]),
        "negative": frozenset(["print(", "console.log(", "System.out.println", "puts ", "p ", "echo ", "var_dump(", "dd(", "fmt.Println", "println!"]),
        "advice": "Use structured logging, avoid print statements",
    },
    {
        "id": "R53",
        "name": "Audit Trail",
        "layer": "static_rules",
        "category": "Compliance",
        "severity": "medium",
        "pts": 4,
        "keywords": frozenset(["audit", "audit_log", "audit_trail", "AuditLog", "event_log", "activity_log", "created_by", "updated_by", "modified_by", "deleted_by", "created_at", "updated_at", "modified_at", "deleted_at", "action_log", "change_log", "changelog", "history", "versioning", "paper_trail", "PaperTrail", "django-auditlog", "django-simple-history", "audited", "acts_as_audited", "Envers", "Hibernate_Envers", "temporal", "bitemporal"]),
        "negative": frozenset([]),
        "advice": "Implement audit logging for compliance",
    },
    {
        "id": "R54",
        "name": "Error Alerting",
        "layer": "static_rules",
        "category": "Compliance",
        "severity": "high",
        "pts": 5,
        "keywords": frozenset(["sentry", "Sentry", "sentry-sdk", "@sentry/node", "@sentry/react", "@sentry/browser", "capture_exception", "captureException", "capture_message", "captureMessage", "pagerduty", "PagerDuty", "opsgenie", "OpsGenie", "victorops", "VictorOps", "datadog", "Datadog", "newrelic", "NewRelic", "rollbar", "Rollbar", "bugsnag", "BugSnag", "airbrake", "Airbrake", "honeybadger", "Honeybadger", "raygun", "Raygun", "elastic-apm", "ElasticAPM", "AppInsights", "Application_Insights", "crashlytics", "Firebase_Crashlytics", "alertmanager", "AlertManager", "prometheus_alerting"]),
        "negative": frozenset([]),
        "advice": "Set up error alerting and monitoring",
    },
    {
        "id": "R55",
        "name": "Request ID Tracking",
        "layer": "static_rules",
        "category": "Compliance",
        "severity": "medium",
        "pts": 3,
        "keywords": frozenset(["request_id", "requestId", "RequestId", "X-Request-ID", "X-Request-Id", "trace_id", "traceId", "TraceId", "correlation_id", "correlationId", "CorrelationId", "X-Correlation-ID", "span_id", "spanId", "SpanId", "opentelemetry", "OpenTelemetry", "jaeger", "Jaeger", "zipkin", "Zipkin", "otel", "OTEL", "tracer", "Tracer", "distributed_tracing", "tracing_middleware", "asgi_correlation_id", "flask_request_id", "express-request-id", "cls-hooked", "async_hooks"]),
        "negative": frozenset([]),
        "advice": "Track requests with unique IDs for debugging",
    },
    {
        "id": "R56",
        "name": "Graceful Shutdown",
        "layer": "static_rules",
        "category": "Compliance",
        "severity": "medium",
        "pts": 3,
        "keywords": frozenset(["on_shutdown", "on_event(\"shutdown\")", "lifespan", "SIGTERM", "SIGINT", "signal.signal", "process.on('SIGTERM')", "process.on('SIGINT')", "graceful", "graceful_shutdown", "GracefulShutdown", "shutdown_hook", "@PreDestroy", "DisposableBean", "IHostedService", "StopAsync", "Runtime.addShutdownHook", "at_exit", "atexit", "trap", "Signal.trap", "defer", "context.Done", "ctx.Done", "cancel", "CancellationToken", "drain", "connection_drain", "keep_alive_timeout"]),
        "negative": frozenset([]),
        "advice": "Implement graceful shutdown",
    },
]

# ═══ O(1) LOOKUP DICTIONARIES (built at import time) ═══

KEYWORD_TO_RULES: dict[str, list[str]] = {}
NEGATIVE_TO_RULES: dict[str, list[str]] = {}

for _rule in RULES:
    for _kw in _rule["keywords"]:
        KEYWORD_TO_RULES.setdefault(_kw, []).append(_rule["id"])
    for _neg in _rule["negative"]:
        NEGATIVE_TO_RULES.setdefault(_neg, []).append(_rule["id"])

TOTAL_RULES = 56
TOTAL_PATTERNS = len(KEYWORD_TO_RULES) + len(NEGATIVE_TO_RULES)
